services:
  beekeeper_api:
    container_name: beekeeper_api 
    image: beekeeper_api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    command: sh -c "./scripts/init.sh"
    depends_on:
      - postgres
    env_file:
      .env
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/api"]
      interval: 5s
      retries: 5
      start_period: 10m
    networks:
      - beekeeper_default 
      - queenbee_default
    mem_limit: 1g
    cpus: "2.0"

  postgres:
    image: postgres:18
    container_name: beekeeper_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-beekeeper}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB:-beekeeper}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beekeeper -d beekeeper"]
      interval: 5s
      retries: 5
    networks:
      - beekeeper_default
    mem_limit: 1g
    cpus: "2.0"

  beekeeper_cron:
    container_name: beekeeper_cron
    image: alpine-base
    mem_limit: 1g
    cpus: "2.0"
    restart: always
    build:
      context: ./cron
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_USER: beekeeper
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: beekeeper
      DB_HOST: postgres

networks:
  beekeeper_default:
    external: false
  queenbee_default:
    external: true

volumes:
  postgres_data:
